version: "3"
services:
  node-app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    image: Telyson/custom_nodeapp:0.0.0.1

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
